name: Deploy ASETEC Eventos to Kinsta

on:
  push:
    branches:
      - main   # despliega cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ajusta local-dir según tu estructura de repo (ver nota abajo)
      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          server-dir: ${{ secrets.SFTP_PATH }}
          local-dir: ./asetec-eventos
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
