name: Deploy ASETEC Eventos to Kinsta

on:
  push:
    branches: [ "main" ]   # despliega cuando hagas push a main
  workflow_dispatch:       # permite lanzarlo manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: "./asetec-eventos/*"
          remote_path: ${{ secrets.SFTP_PATH }}
          sftp_only: true
