name: Deploy ASETEC Eventos to Kinsta

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: deploy-asetec-eventos
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ver archivos locales
        run: ls -la asetec-eventos || (echo "❌ Falta carpeta asetec-eventos" && exit 1)

      - name: SSH - verificar carpeta remota
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            set -e
            PLUGINDIR="/www/internoaseteccom_556/public/wp-content/plugins/asetec-eventos"
            mkdir -p "$PLUGINDIR"
            echo "Contenido en $PLUGINDIR:"
            ls -la "$PLUGINDIR"

      - name: SCP - subir plugin
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          source: "asetec-eventos/*"   # copia el contenido de la carpeta
          target: "/www/internoaseteccom_556/public/wp-content/plugins/asetec-eventos"
          overwrite: true
          rm: true                     # limpia el destino antes de copiar
