name: Deploy ASETEC Eventos to Kinsta

on:
  push:
    branches: [ "main" ]     # despliega con push a main
  workflow_dispatch:          # permite ejecutarlo manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          protocol: "sftp"
          server-dir: ${{ secrets.SFTP_PATH }}
          local-dir: "./asetec-eventos/"   # <- barra final obligatoria
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
