name: Deploy ASETEC Eventos to Kinsta

on:
  push:
    branches: ["main"]       # despliega en push a main
  workflow_dispatch:         # permite ejecutarlo manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Validar que exista la carpeta local
      - name: Ver archivos locales
        run: ls -la asetec-eventos || (echo "❌ No existe la carpeta asetec-eventos" && exit 1)

      # Conectarse por SSH y verificar carpeta destino
      - name: SSH - Verificar carpeta remota
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            set -e
            PLUGINDIR="/www/internoaseteccom_556/public/wp-content/plugins/asetec-eventos"
            echo "Verificando carpeta destino: $PLUGINDIR"
            mkdir -p "$PLUGINDIR"
            ls -la "$PLUGINDIR"

      # Subir los archivos del plugin
      - name: SCP - Deploy plugin
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          source: "asetec-eventos/**"
          target: "/www/internoaseteccom_556/public/wp-content/plugins/asetec-eventos"
          overwrite: true
          rm: true                  # limpia antes de copiar
          strip_components: 1       # evita carpeta extra dentro del destino
